---
- include_tasks: centos_content.yml

- name: Check that manifest exists
  local_action: stat path="{{ katello_provisioning_manifest_path }}"
  register: manifest_stat
  become: no
  when: katello_provisioning_manifest_path is defined

- include_tasks: manifest_upload.yml
  when: katello_provisioning_manifest_path is defined and manifest_result.stat.exists

  # Create repositories when either a manifest is provided or it was imported to Katello before
- include_tasks: redhat_content.yml
  when: (katello_provisioning_manifest_path is defined and manifest_result.state.exists) or katello_provisioning_manifest_preloaded
